// Code generated by command: go run main.go -out fftc_batch_amd64.s -stubs fftc_batch_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA fftc_batch_jrot_sign<>+0(SB)/4, $0x00000000
DATA fftc_batch_jrot_sign<>+4(SB)/4, $0x80000000
DATA fftc_batch_jrot_sign<>+8(SB)/4, $0x00000000
DATA fftc_batch_jrot_sign<>+12(SB)/4, $0x80000000
DATA fftc_batch_jrot_sign<>+16(SB)/4, $0x00000000
DATA fftc_batch_jrot_sign<>+20(SB)/4, $0x80000000
DATA fftc_batch_jrot_sign<>+24(SB)/4, $0x00000000
DATA fftc_batch_jrot_sign<>+28(SB)/4, $0x80000000
GLOBL fftc_batch_jrot_sign<>(SB), RODATA|NOPTR, $32

DATA fftc_batch_neg_half<>+0(SB)/4, $0xbf000000
GLOBL fftc_batch_neg_half<>(SB), RODATA|NOPTR, $4

DATA fftc_batch_sqrt3_over_2<>+0(SB)/4, $0x3f5db3d7
GLOBL fftc_batch_sqrt3_over_2<>(SB), RODATA|NOPTR, $4

// func packBatch4AVX2(dst []complex64, src []complex64, n int)
// Requires: AVX, AVX2
TEXT ·packBatch4AVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), AX
	MOVQ src_base+24(FP), CX
	MOVQ n+48(FP), DX
	SHLQ $0x03, DX
	LEAQ (CX)(DX*1), BX
	LEAQ (BX)(DX*1), SI
	LEAQ (SI)(DX*1), DI
	XORQ R8, R8

pack_loop:
	CMPQ        R8, DX
	JGE         pack_done
	VMOVQ       (CX)(R8*1), X0
	VMOVQ       (BX)(R8*1), X1
	VMOVQ       (SI)(R8*1), X2
	VMOVQ       (DI)(R8*1), X3
	VPUNPCKLQDQ X1, X0, X0
	VPUNPCKLQDQ X3, X2, X1
	VINSERTI128 $0x00, X0, Y4, Y4
	VINSERTI128 $0x01, X1, Y4, Y4
	VMOVUPS     Y4, (AX)(R8*4)
	ADDQ        $0x08, R8
	JMP         pack_loop

pack_done:
	VZEROUPPER
	RET

// func unpackBatch4AVX2(dst []complex64, src []complex64, n int)
// Requires: AVX, AVX2
TEXT ·unpackBatch4AVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), AX
	MOVQ src_base+24(FP), CX
	MOVQ n+48(FP), DX
	SHLQ $0x03, DX
	LEAQ (AX)(DX*1), BX
	LEAQ (BX)(DX*1), SI
	LEAQ (SI)(DX*1), DI
	XORQ R8, R8

unpack_loop:
	CMPQ         R8, DX
	JGE          unpack_done
	VMOVUPS      (CX)(R8*4), Y0
	VEXTRACTI128 $0x00, Y0, X1
	VEXTRACTI128 $0x01, Y0, X0
	VMOVQ        X1, (AX)(R8*1)
	VPSRLDQ      $0x08, X1, X1
	VMOVQ        X1, (BX)(R8*1)
	VMOVQ        X0, (SI)(R8*1)
	VPSRLDQ      $0x08, X0, X1
	VMOVQ        X1, (DI)(R8*1)
	ADDQ         $0x08, R8
	JMP          unpack_loop

unpack_done:
	VZEROUPPER
	RET

// func stockhamRadix2AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)
// Requires: AVX, FMA3
TEXT ·stockhamRadix2AVX2(SB), NOSPLIT, $0-96
	MOVQ dst_base+0(FP), CX
	MOVQ src_base+24(FP), BX
	MOVQ tw_base+48(FP), SI
	MOVQ butterflies+72(FP), DI
	MOVQ sections+80(FP), R8
	MOVQ n+88(FP), AX
	XORQ DX, DX
	MOVQ $0x0000000000000002, R9
	DIVQ R9
	MOVQ AX, AX
	SHLQ $0x05, AX
	MOVQ DI, DX
	SHLQ $0x05, DX
	MOVQ SI, R9
	XORQ R10, R10

stockhamRadix2AVX2_section:
	CMPQ R10, R8
	JGE  stockhamRadix2AVX2_done
	XORQ R11, R11

stockhamRadix2AVX2_p:
	CMPQ           R11, DI
	JGE            stockhamRadix2AVX2_next_section
	VMOVUPS        (BX), Y0
	VMOVUPS        (BX)(AX*1), Y1
	VBROADCASTSD   (R9), Y2
	VSHUFPS        $0xa0, Y2, Y2, Y3
	VSHUFPS        $0xf5, Y2, Y2, Y2
	VPERMILPS      $0xb1, Y1, Y4
	VMULPS         Y2, Y4, Y2
	VFMADDSUB231PS Y1, Y3, Y2
	VADDPS         Y2, Y0, Y1
	VSUBPS         Y2, Y0, Y0
	VMOVUPS        Y1, (CX)
	VMOVUPS        Y0, (CX)(DX*1)
	INCQ           R11
	ADDQ           $0x20, BX
	ADDQ           $0x20, CX
	ADDQ           $0x08, R9
	JMP            stockhamRadix2AVX2_p

stockhamRadix2AVX2_next_section:
	ADDQ DX, CX
	MOVQ SI, R9
	INCQ R10
	JMP  stockhamRadix2AVX2_section

stockhamRadix2AVX2_done:
	VZEROUPPER
	RET

// func stockhamRadix3AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)
// Requires: AVX, FMA3
TEXT ·stockhamRadix3AVX2(SB), NOSPLIT, $0-96
	MOVQ         dst_base+0(FP), CX
	MOVQ         src_base+24(FP), BX
	MOVQ         tw_base+48(FP), SI
	MOVQ         butterflies+72(FP), DI
	MOVQ         sections+80(FP), R8
	MOVQ         n+88(FP), AX
	XORQ         DX, DX
	MOVQ         $0x0000000000000003, R9
	DIVQ         R9
	MOVQ         AX, AX
	SHLQ         $0x05, AX
	MOVQ         DI, DX
	SHLQ         $0x05, DX
	MOVQ         DX, R9
	SHLQ         $0x01, R9
	MOVQ         DI, R10
	SHLQ         $0x03, R10
	MOVQ         SI, R11
	VMOVUPS      fftc_batch_jrot_sign<>+0(SB), Y0
	VBROADCASTSS fftc_batch_neg_half<>+0(SB), Y1
	VBROADCASTSS fftc_batch_sqrt3_over_2<>+0(SB), Y2
	XORQ         R12, R12

stockhamRadix3AVX2_section:
	CMPQ R12, R8
	JGE  stockhamRadix3AVX2_done
	XORQ R13, R13

stockhamRadix3AVX2_p:
	CMPQ           R13, DI
	JGE            stockhamRadix3AVX2_next_section
	VMOVUPS        (BX), Y3
	VMOVUPS        (BX)(AX*1), Y4
	VBROADCASTSD   (R11), Y5
	VSHUFPS        $0xa0, Y5, Y5, Y6
	VSHUFPS        $0xf5, Y5, Y5, Y5
	VPERMILPS      $0xb1, Y4, Y7
	VMULPS         Y5, Y7, Y5
	VFMADDSUB231PS Y4, Y6, Y5
	VMOVUPS        (BX)(AX*2), Y4
	VBROADCASTSD   (R11)(R10*1), Y6
	VSHUFPS        $0xa0, Y6, Y6, Y7
	VSHUFPS        $0xf5, Y6, Y6, Y6
	VPERMILPS      $0xb1, Y4, Y8
	VMULPS         Y6, Y8, Y6
	VFMADDSUB231PS Y4, Y7, Y6
	VADDPS         Y6, Y5, Y4
	VSUBPS         Y6, Y5, Y5
	VADDPS         Y4, Y3, Y6
	VMULPS         Y1, Y4, Y4
	VADDPS         Y4, Y3, Y3
	VMULPS         Y2, Y5, Y4
	VPERMILPS      $0xb1, Y4, Y4
	VXORPS         Y0, Y4, Y4
	VADDPS         Y4, Y3, Y5
	VSUBPS         Y4, Y3, Y3
	VMOVUPS        Y6, (CX)
	VMOVUPS        Y5, (CX)(DX*1)
	VMOVUPS        Y3, (CX)(DX*2)
	INCQ           R13
	ADDQ           $0x20, BX
	ADDQ           $0x20, CX
	ADDQ           $0x08, R11
	JMP            stockhamRadix3AVX2_p

stockhamRadix3AVX2_next_section:
	ADDQ R9, CX
	MOVQ SI, R11
	INCQ R12
	JMP  stockhamRadix3AVX2_section

stockhamRadix3AVX2_done:
	VZEROUPPER
	RET

// func stockhamRadix4AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)
// Requires: AVX, FMA3
TEXT ·stockhamRadix4AVX2(SB), NOSPLIT, $0-96
	MOVQ    dst_base+0(FP), CX
	MOVQ    src_base+24(FP), BX
	MOVQ    tw_base+48(FP), SI
	MOVQ    butterflies+72(FP), DI
	MOVQ    sections+80(FP), R8
	MOVQ    n+88(FP), AX
	XORQ    DX, DX
	MOVQ    $0x0000000000000004, R9
	DIVQ    R9
	MOVQ    AX, AX
	SHLQ    $0x05, AX
	LEAQ    (AX)(AX*2), DX
	MOVQ    DI, R9
	SHLQ    $0x05, R9
	LEAQ    (R9)(R9*2), R10
	MOVQ    DI, R11
	SHLQ    $0x03, R11
	MOVQ    SI, R12
	VMOVUPS fftc_batch_jrot_sign<>+0(SB), Y0
	XORQ    R13, R13

stockhamRadix4AVX2_section:
	CMPQ R13, R8
	JGE  stockhamRadix4AVX2_done
	XORQ R14, R14

stockhamRadix4AVX2_p:
	CMPQ           R14, DI
	JGE            stockhamRadix4AVX2_next_section
	VMOVUPS        (BX), Y1
	VMOVUPS        (BX)(AX*1), Y2
	VBROADCASTSD   (R12), Y3
	VSHUFPS        $0xa0, Y3, Y3, Y4
	VSHUFPS        $0xf5, Y3, Y3, Y3
	VPERMILPS      $0xb1, Y2, Y5
	VMULPS         Y3, Y5, Y3
	VFMADDSUB231PS Y2, Y4, Y3
	VMOVUPS        (BX)(AX*2), Y2
	VBROADCASTSD   (R12)(R11*1), Y4
	VSHUFPS        $0xa0, Y4, Y4, Y5
	VSHUFPS        $0xf5, Y4, Y4, Y4
	VPERMILPS      $0xb1, Y2, Y6
	VMULPS         Y4, Y6, Y4
	VFMADDSUB231PS Y2, Y5, Y4
	VMOVUPS        (BX)(DX*1), Y2
	VBROADCASTSD   (R12)(R11*2), Y5
	VSHUFPS        $0xa0, Y5, Y5, Y6
	VSHUFPS        $0xf5, Y5, Y5, Y5
	VPERMILPS      $0xb1, Y2, Y7
	VMULPS         Y5, Y7, Y5
	VFMADDSUB231PS Y2, Y6, Y5
	VSUBPS         Y4, Y1, Y2
	VADDPS         Y4, Y1, Y1
	VADDPS         Y5, Y3, Y4
	VSUBPS         Y5, Y3, Y3
	VADDPS         Y4, Y1, Y5
	VSUBPS         Y4, Y1, Y1
	VPERMILPS      $0xb1, Y3, Y3
	VXORPS         Y0, Y3, Y3
	VADDPS         Y3, Y2, Y4
	VSUBPS         Y3, Y2, Y2
	VMOVUPS        Y5, (CX)
	VMOVUPS        Y4, (CX)(R9*1)
	VMOVUPS        Y1, (CX)(R9*2)
	VMOVUPS        Y2, (CX)(R10*1)
	INCQ           R14
	ADDQ           $0x20, BX
	ADDQ           $0x20, CX
	ADDQ           $0x08, R12
	JMP            stockhamRadix4AVX2_p

stockhamRadix4AVX2_next_section:
	ADDQ R10, CX
	MOVQ SI, R12
	INCQ R13
	JMP  stockhamRadix4AVX2_section

stockhamRadix4AVX2_done:
	VZEROUPPER
	RET

// func stockhamRadix5AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)
// Requires: AVX, FMA3
TEXT ·stockhamRadix5AVX2(SB), NOSPLIT, $8-96
	MOVQ         dst_base+0(FP), CX
	MOVQ         src_base+24(FP), BX
	MOVQ         tw_base+48(FP), SI
	MOVQ         butterflies+72(FP), DI
	MOVQ         sections+80(FP), R8
	MOVQ         n+88(FP), AX
	XORQ         DX, DX
	MOVQ         $0x0000000000000005, R9
	DIVQ         R9
	MOVQ         AX, AX
	SHLQ         $0x05, AX
	LEAQ         (AX)(AX*2), DX
	MOVQ         DI, R9
	SHLQ         $0x05, R9
	LEAQ         (R9)(R9*2), R10
	MOVQ         R9, R11
	SHLQ         $0x02, R11
	MOVQ         DI, R12
	SHLQ         $0x03, R12
	LEAQ         (R12)(R12*2), R13
	MOVQ         SI, R14
	VMOVUPS      fftc_batch_jrot_sign<>+0(SB), Y0
	VBROADCASTSS fftc_batch_radix5_c1<>+0(SB), Y1
	VBROADCASTSS fftc_batch_radix5_c2<>+0(SB), Y2
	VBROADCASTSS fftc_batch_radix5_s1<>+0(SB), Y3
	VBROADCASTSS fftc_batch_radix5_s2<>+0(SB), Y4
	XORQ         R15, R15

stockhamRadix5AVX2_section:
	CMPQ R15, R8
	JGE  stockhamRadix5AVX2_done
	XORQ BP, BP

stockhamRadix5AVX2_p:
	CMPQ           BP, DI
	JGE            stockhamRadix5AVX2_next_section
	VMOVUPS        (BX), Y5
	VMOVUPS        (BX)(AX*1), Y6
	VBROADCASTSD   (R14), Y7
	VSHUFPS        $0xa0, Y7, Y7, Y8
	VSHUFPS        $0xf5, Y7, Y7, Y7
	VPERMILPS      $0xb1, Y6, Y9
	VMULPS         Y7, Y9, Y7
	VFMADDSUB231PS Y6, Y8, Y7
	VMOVUPS        (BX)(AX*2), Y6
	VBROADCASTSD   (R14)(R12*1), Y8
	VSHUFPS        $0xa0, Y8, Y8, Y9
	VSHUFPS        $0xf5, Y8, Y8, Y8
	VPERMILPS      $0xb1, Y6, Y10
	VMULPS         Y8, Y10, Y8
	VFMADDSUB231PS Y6, Y9, Y8
	VMOVUPS        (BX)(DX*1), Y6
	VBROADCASTSD   (R14)(R12*2), Y9
	VSHUFPS        $0xa0, Y9, Y9, Y10
	VSHUFPS        $0xf5, Y9, Y9, Y9
	VPERMILPS      $0xb1, Y6, Y11
	VMULPS         Y9, Y11, Y9
	VFMADDSUB231PS Y6, Y10, Y9
	VMOVUPS        (BX)(AX*4), Y6
	VBROADCASTSD   (R14)(R13*1), Y10
	VSHUFPS        $0xa0, Y10, Y10, Y11
	VSHUFPS        $0xf5, Y10, Y10, Y10
	VPERMILPS      $0xb1, Y6, Y12
	VMULPS         Y10, Y12, Y10
	VFMADDSUB231PS Y6, Y11, Y10
	VADDPS         Y10, Y7, Y6
	VSUBPS         Y10, Y7, Y7
	VADDPS         Y9, Y8, Y10
	VSUBPS         Y9, Y8, Y8
	VADDPS         Y6, Y5, Y9
	VADDPS         Y10, Y9, Y9
	VMULPS         Y1, Y6, Y11
	VMULPS         Y2, Y10, Y12
	VADDPS         Y11, Y5, Y11
	VADDPS         Y12, Y11, Y11
	VMULPS         Y2, Y6, Y6
	VMULPS         Y1, Y10, Y10
	VADDPS         Y6, Y5, Y5
	VADDPS         Y10, Y5, Y5
	VMULPS         Y3, Y7, Y6
	VMULPS         Y4, Y8, Y10
	VADDPS         Y10, Y6, Y6
	VMULPS         Y4, Y7, Y7
	VMULPS         Y3, Y8, Y8
	VSUBPS         Y8, Y7, Y7
	VPERMILPS      $0xb1, Y6, Y6
	VXORPS         Y0, Y6, Y6
	VPERMILPS      $0xb1, Y7, Y7
	VXORPS         Y0, Y7, Y7
	VADDPS         Y6, Y11, Y8
	VSUBPS         Y6, Y11, Y6
	VADDPS         Y7, Y5, Y10
	VSUBPS         Y7, Y5, Y5
	VMOVUPS        Y9, (CX)
	VMOVUPS        Y8, (CX)(R9*1)
	VMOVUPS        Y10, (CX)(R9*2)
	VMOVUPS        Y5, (CX)(R10*1)
	VMOVUPS        Y6, (CX)(R9*4)
	INCQ           BP
	ADDQ           $0x20, BX
	ADDQ           $0x20, CX
	ADDQ           $0x08, R14
	JMP            stockhamRadix5AVX2_p

stockhamRadix5AVX2_next_section:
	ADDQ R11, CX
	MOVQ SI, R14
	INCQ R15
	JMP  stockhamRadix5AVX2_section

stockhamRadix5AVX2_done:
	VZEROUPPER
	RET

DATA fftc_batch_radix5_c1<>+0(SB)/4, $0x3e9e377a
GLOBL fftc_batch_radix5_c1<>(SB), RODATA|NOPTR, $4

DATA fftc_batch_radix5_c2<>+0(SB)/4, $0xbf4f1bbd
GLOBL fftc_batch_radix5_c2<>(SB), RODATA|NOPTR, $4

DATA fftc_batch_radix5_s1<>+0(SB)/4, $0x3f737871
GLOBL fftc_batch_radix5_s1<>(SB), RODATA|NOPTR, $4

DATA fftc_batch_radix5_s2<>+0(SB)/4, $0x3f167918
GLOBL fftc_batch_radix5_s2<>(SB), RODATA|NOPTR, $4

// func stockhamRadix4PackAVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)
// Requires: AVX, AVX2, FMA3
TEXT ·stockhamRadix4PackAVX2(SB), NOSPLIT, $0-96
	MOVQ    dst_base+0(FP), CX
	MOVQ    src_base+24(FP), BX
	MOVQ    tw_base+48(FP), SI
	MOVQ    butterflies+72(FP), AX
	MOVQ    sections+80(FP), DI
	MOVQ    n+88(FP), R8
	MOVQ    R8, AX
	XORQ    DX, DX
	MOVQ    $0x0000000000000004, R9
	DIVQ    R9
	MOVQ    SI, DX
	MOVQ    R8, SI
	SHLQ    $0x03, SI
	LEAQ    (BX)(SI*1), R8
	LEAQ    (R8)(SI*1), R9
	LEAQ    (R9)(SI*1), SI
	MOVQ    AX, R10
	SHLQ    $0x03, R10
	LEAQ    (R10)(R10*2), R11
	VMOVUPS fftc_batch_jrot_sign<>+0(SB), Y0
	XORQ    AX, AX

stockhamRadix4PackAVX2_section:
	CMPQ           AX, DI
	JGE            stockhamRadix4PackAVX2_done
	VMOVQ          (BX), X2
	VMOVQ          (R8), X3
	VMOVQ          (R9), X4
	VMOVQ          (SI), X5
	VPUNPCKLQDQ    X3, X2, X2
	VPUNPCKLQDQ    X5, X4, X3
	VINSERTI128    $0x00, X2, Y1, Y1
	VINSERTI128    $0x01, X3, Y1, Y1
	VMOVQ          (BX)(R10*1), X2
	VMOVQ          (R8)(R10*1), X3
	VMOVQ          (R9)(R10*1), X4
	VMOVQ          (SI)(R10*1), X5
	VPUNPCKLQDQ    X3, X2, X2
	VPUNPCKLQDQ    X5, X4, X3
	VINSERTI128    $0x00, X2, Y6, Y6
	VINSERTI128    $0x01, X3, Y6, Y6
	VBROADCASTSD   (DX), Y2
	VSHUFPS        $0xa0, Y2, Y2, Y3
	VSHUFPS        $0xf5, Y2, Y2, Y2
	VPERMILPS      $0xb1, Y6, Y4
	VMULPS         Y2, Y4, Y2
	VFMADDSUB231PS Y6, Y3, Y2
	VMOVQ          (BX)(R10*2), X3
	VMOVQ          (R8)(R10*2), X4
	VMOVQ          (R9)(R10*2), X5
	VMOVQ          (SI)(R10*2), X9
	VPUNPCKLQDQ    X4, X3, X3
	VPUNPCKLQDQ    X9, X5, X4
	VINSERTI128    $0x00, X3, Y7, Y7
	VINSERTI128    $0x01, X4, Y7, Y7
	VBROADCASTSD   8(DX), Y3
	VSHUFPS        $0xa0, Y3, Y3, Y4
	VSHUFPS        $0xf5, Y3, Y3, Y3
	VPERMILPS      $0xb1, Y7, Y5
	VMULPS         Y3, Y5, Y3
	VFMADDSUB231PS Y7, Y4, Y3
	VMOVQ          (BX)(R11*1), X4
	VMOVQ          (R8)(R11*1), X5
	VMOVQ          (R9)(R11*1), X9
	VMOVQ          (SI)(R11*1), X10
	VPUNPCKLQDQ    X5, X4, X4
	VPUNPCKLQDQ    X10, X9, X5
	VINSERTI128    $0x00, X4, Y8, Y8
	VINSERTI128    $0x01, X5, Y8, Y8
	VBROADCASTSD   16(DX), Y4
	VSHUFPS        $0xa0, Y4, Y4, Y5
	VSHUFPS        $0xf5, Y4, Y4, Y4
	VPERMILPS      $0xb1, Y8, Y9
	VMULPS         Y4, Y9, Y4
	VFMADDSUB231PS Y8, Y5, Y4
	VSUBPS         Y3, Y1, Y5
	VADDPS         Y3, Y1, Y3
	VADDPS         Y4, Y2, Y9
	VSUBPS         Y4, Y2, Y2
	VADDPS         Y9, Y3, Y4
	VSUBPS         Y9, Y3, Y3
	VPERMILPS      $0xb1, Y2, Y2
	VXORPS         Y0, Y2, Y2
	VADDPS         Y2, Y5, Y9
	VSUBPS         Y2, Y5, Y2
	VMOVUPS        Y4, (CX)
	VMOVUPS        Y9, 32(CX)
	VMOVUPS        Y3, 64(CX)
	VMOVUPS        Y2, 96(CX)
	ADDQ           $0x80, CX
	ADDQ           $0x08, BX
	ADDQ           $0x08, R8
	ADDQ           $0x08, R9
	ADDQ           $0x08, SI
	INCQ           AX
	JMP            stockhamRadix4PackAVX2_section

stockhamRadix4PackAVX2_done:
	VZEROUPPER
	RET

// func stockhamRadix3UnpackAVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)
// Requires: AVX, AVX2, FMA3
TEXT ·stockhamRadix3UnpackAVX2(SB), NOSPLIT, $0-96
	MOVQ         dst_base+0(FP), CX
	MOVQ         src_base+24(FP), BX
	MOVQ         tw_base+48(FP), SI
	MOVQ         butterflies+72(FP), DI
	MOVQ         sections+80(FP), AX
	MOVQ         n+88(FP), R8
	MOVQ         R8, AX
	XORQ         DX, DX
	MOVQ         $0x0000000000000003, R9
	DIVQ         R9
	MOVQ         AX, AX
	SHLQ         $0x05, AX
	MOVQ         DI, DX
	SHLQ         $0x03, DX
	MOVQ         R8, R8
	SHLQ         $0x03, R8
	LEAQ         (CX)(R8*1), R9
	LEAQ         (R9)(R8*1), R10
	LEAQ         (R10)(R8*1), R11
	VMOVUPS      fftc_batch_jrot_sign<>+0(SB), Y0
	VBROADCASTSS fftc_batch_neg_half<>+0(SB), Y1
	VBROADCASTSS fftc_batch_sqrt3_over_2<>+0(SB), Y2
	XORQ         R8, R8

stockhamRadix3UnpackAVX2_p:
	CMPQ           R8, DI
	JGE            stockhamRadix3UnpackAVX2_done
	VMOVUPS        (BX), Y3
	VMOVUPS        (BX)(AX*1), Y4
	VBROADCASTSD   (SI), Y5
	VSHUFPS        $0xa0, Y5, Y5, Y6
	VSHUFPS        $0xf5, Y5, Y5, Y5
	VPERMILPS      $0xb1, Y4, Y7
	VMULPS         Y5, Y7, Y5
	VFMADDSUB231PS Y4, Y6, Y5
	VMOVUPS        (BX)(AX*2), Y4
	VBROADCASTSD   (SI)(DX*1), Y6
	VSHUFPS        $0xa0, Y6, Y6, Y7
	VSHUFPS        $0xf5, Y6, Y6, Y6
	VPERMILPS      $0xb1, Y4, Y8
	VMULPS         Y6, Y8, Y6
	VFMADDSUB231PS Y4, Y7, Y6
	VADDPS         Y6, Y5, Y4
	VSUBPS         Y6, Y5, Y5
	VADDPS         Y4, Y3, Y6
	VMULPS         Y1, Y4, Y4
	VADDPS         Y4, Y3, Y3
	VMULPS         Y2, Y5, Y4
	VPERMILPS      $0xb1, Y4, Y4
	VXORPS         Y0, Y4, Y4
	VADDPS         Y4, Y3, Y5
	VSUBPS         Y4, Y3, Y3
	VEXTRACTI128   $0x00, Y6, X4
	VEXTRACTI128   $0x01, Y6, X6
	VMOVQ          X4, (CX)
	VPSRLDQ        $0x08, X4, X4
	VMOVQ          X4, (R9)
	VMOVQ          X6, (R10)
	VPSRLDQ        $0x08, X6, X4
	VMOVQ          X4, (R11)
	VEXTRACTI128   $0x00, Y5, X4
	VEXTRACTI128   $0x01, Y5, X5
	VMOVQ          X4, (CX)(DX*1)
	VPSRLDQ        $0x08, X4, X4
	VMOVQ          X4, (R9)(DX*1)
	VMOVQ          X5, (R10)(DX*1)
	VPSRLDQ        $0x08, X5, X4
	VMOVQ          X4, (R11)(DX*1)
	VEXTRACTI128   $0x00, Y3, X4
	VEXTRACTI128   $0x01, Y3, X3
	VMOVQ          X4, (CX)(DX*2)
	VPSRLDQ        $0x08, X4, X4
	VMOVQ          X4, (R9)(DX*2)
	VMOVQ          X3, (R10)(DX*2)
	VPSRLDQ        $0x08, X3, X4
	VMOVQ          X4, (R11)(DX*2)
	INCQ           R8
	ADDQ           $0x20, BX
	ADDQ           $0x08, SI
	ADDQ           $0x08, CX
	ADDQ           $0x08, R9
	ADDQ           $0x08, R10
	ADDQ           $0x08, R11
	JMP            stockhamRadix3UnpackAVX2_p

stockhamRadix3UnpackAVX2_done:
	VZEROUPPER
	RET
