// Code generated by command: go run main.go -out fftc_amd64.s -stubs fftc_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

package dsp

// bfly4AVX2 computes radix-4 FFTC butterflies for k in [0,mv), four complex lanes per iteration; the Go dispatch handles the scalar tail.
func bfly4AVX2(out []complex64, tw []complex64, mv int, m int)

// bfly3AVX2 computes radix-3 FFTC butterflies for k in [0,mv), four complex lanes per iteration; the Go dispatch handles the scalar tail.
func bfly3AVX2(out []complex64, tw []complex64, mv int, m int)
