// Code generated by command: go run main.go -out fftc_amd64.s -stubs fftc_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA fftc_jrot_sign<>+0(SB)/4, $0x00000000
DATA fftc_jrot_sign<>+4(SB)/4, $0x80000000
DATA fftc_jrot_sign<>+8(SB)/4, $0x00000000
DATA fftc_jrot_sign<>+12(SB)/4, $0x80000000
DATA fftc_jrot_sign<>+16(SB)/4, $0x00000000
DATA fftc_jrot_sign<>+20(SB)/4, $0x80000000
DATA fftc_jrot_sign<>+24(SB)/4, $0x00000000
DATA fftc_jrot_sign<>+28(SB)/4, $0x80000000
GLOBL fftc_jrot_sign<>(SB), RODATA|NOPTR, $32

// func bfly4AVX2(out []complex64, tw []complex64, mv int, m int)
// Requires: AVX, FMA3
TEXT ·bfly4AVX2(SB), NOSPLIT, $0-64
	MOVQ    out_base+0(FP), AX
	MOVQ    tw_base+24(FP), CX
	MOVQ    mv+48(FP), DX
	MOVQ    m+56(FP), BX
	VMOVUPS fftc_jrot_sign<>+0(SB), Y0
	XORQ    SI, SI

loop:
	CMPQ           SI, DX
	JGE            done
	LEAQ           (AX)(SI*8), DI
	LEAQ           (DI)(BX*8), R8
	LEAQ           (R8)(BX*8), R9
	LEAQ           (R9)(BX*8), R10
	LEAQ           (CX)(SI*8), R11
	LEAQ           (R11)(BX*8), R12
	LEAQ           (R12)(BX*8), R13
	VMOVUPS        (DI), Y1
	VMOVUPS        (R8), Y2
	VMOVUPS        (R9), Y3
	VMOVUPS        (R10), Y4
	VMOVUPS        (R11), Y5
	VMOVUPS        (R12), Y6
	VMOVUPS        (R13), Y7
	VSHUFPS        $0xa0, Y5, Y5, Y8
	VSHUFPS        $0xf5, Y5, Y5, Y5
	VPERMILPS      $0xb1, Y2, Y9
	VMULPS         Y5, Y9, Y5
	VFMADDSUB231PS Y2, Y8, Y5
	VSHUFPS        $0xa0, Y6, Y6, Y2
	VSHUFPS        $0xf5, Y6, Y6, Y6
	VPERMILPS      $0xb1, Y3, Y8
	VMULPS         Y6, Y8, Y6
	VFMADDSUB231PS Y3, Y2, Y6
	VSHUFPS        $0xa0, Y7, Y7, Y2
	VSHUFPS        $0xf5, Y7, Y7, Y3
	VPERMILPS      $0xb1, Y4, Y7
	VMULPS         Y3, Y7, Y3
	VFMADDSUB231PS Y4, Y2, Y3
	VSUBPS         Y6, Y1, Y2
	VADDPS         Y6, Y1, Y1
	VADDPS         Y3, Y5, Y4
	VSUBPS         Y3, Y5, Y3
	VADDPS         Y4, Y1, Y5
	VSUBPS         Y4, Y1, Y1
	VPERMILPS      $0xb1, Y3, Y3
	VXORPS         Y0, Y3, Y3
	VADDPS         Y3, Y2, Y4
	VSUBPS         Y3, Y2, Y2
	VMOVUPS        Y5, (DI)
	VMOVUPS        Y4, (R8)
	VMOVUPS        Y1, (R9)
	VMOVUPS        Y2, (R10)
	ADDQ           $0x04, SI
	JMP            loop

done:
	VZEROUPPER
	RET

// func bfly3AVX2(out []complex64, tw []complex64, mv int, m int)
// Requires: AVX, FMA3
TEXT ·bfly3AVX2(SB), NOSPLIT, $0-64
	MOVQ         out_base+0(FP), AX
	MOVQ         tw_base+24(FP), CX
	MOVQ         mv+48(FP), DX
	MOVQ         m+56(FP), BX
	VMOVUPS      fftc_jrot_sign<>+0(SB), Y0
	VBROADCASTSS fftc_neg_half<>+0(SB), Y1
	VBROADCASTSS fftc_sqrt3_over_2<>+0(SB), Y2
	XORQ         SI, SI

loop3:
	CMPQ           SI, DX
	JGE            done3
	LEAQ           (AX)(SI*8), DI
	LEAQ           (DI)(BX*8), R8
	LEAQ           (R8)(BX*8), R9
	LEAQ           (CX)(SI*8), R10
	LEAQ           (R10)(BX*8), R11
	VMOVUPS        (DI), Y3
	VMOVUPS        (R8), Y4
	VMOVUPS        (R9), Y5
	VMOVUPS        (R10), Y6
	VMOVUPS        (R11), Y7
	VSHUFPS        $0xa0, Y6, Y6, Y8
	VSHUFPS        $0xf5, Y6, Y6, Y6
	VPERMILPS      $0xb1, Y4, Y9
	VMULPS         Y6, Y9, Y6
	VFMADDSUB231PS Y4, Y8, Y6
	VSHUFPS        $0xa0, Y7, Y7, Y4
	VSHUFPS        $0xf5, Y7, Y7, Y7
	VPERMILPS      $0xb1, Y5, Y8
	VMULPS         Y7, Y8, Y7
	VFMADDSUB231PS Y5, Y4, Y7
	VADDPS         Y7, Y6, Y4
	VSUBPS         Y7, Y6, Y5
	VADDPS         Y4, Y3, Y6
	VMULPS         Y1, Y4, Y4
	VADDPS         Y4, Y3, Y3
	VMULPS         Y2, Y5, Y4
	VPERMILPS      $0xb1, Y4, Y4
	VXORPS         Y0, Y4, Y4
	VADDPS         Y4, Y3, Y5
	VSUBPS         Y4, Y3, Y3
	VMOVUPS        Y6, (DI)
	VMOVUPS        Y5, (R8)
	VMOVUPS        Y3, (R9)
	ADDQ           $0x04, SI
	JMP            loop3

done3:
	VZEROUPPER
	RET

DATA fftc_neg_half<>+0(SB)/4, $0xbf000000
GLOBL fftc_neg_half<>(SB), RODATA|NOPTR, $4

DATA fftc_sqrt3_over_2<>+0(SB)/4, $0x3f5db3d7
GLOBL fftc_sqrt3_over_2<>(SB), RODATA|NOPTR, $4
