// Code generated by command: go run main.go -out fftc_batch_amd64.s -stubs fftc_batch_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

package dsp

func packBatch4AVX2(dst []complex64, src []complex64, n int)

func unpackBatch4AVX2(dst []complex64, src []complex64, n int)

func stockhamRadix2AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)

func stockhamRadix3AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)

func stockhamRadix4AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)

func stockhamRadix5AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)

func stockhamRadix8AVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)

func stockhamRadix4PackAVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)

func stockhamRadix3UnpackAVX2(dst []complex64, src []complex64, tw []complex64, butterflies int, sections int, n int)
