// Code generated by command: go run main.go -out filter_amd64.s -stubs filter_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

package dsp

// complexFIRDotAVX2 accumulates the multiple-of-eight FIR prefix with AVX2/FMA.
//
//go:noescape
func complexFIRDotAVX2(taps []float32, winR []float32, winI []float32, n int, out *[2]float32)

// firDotRealAVX2 accumulates the multiple-of-eight real FIR prefix with AVX2/FMA.
//
//go:noescape
func firDotRealAVX2(taps []float32, win []float32, n int, out *float32)

// complexFIRDot4AVX2 accumulates four shared-tap complex FIR prefixes (multiple of eight) in one tap pass; the Go dispatch handles the per-lane scalar tail.
//
//go:noescape
func complexFIRDot4AVX2(taps []float32, winR []float32, winI []float32, stride int, nv int, out *[8]float32)
