// Code generated by command: go run main.go -out filter_amd64.s -stubs filter_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func complexFIRDotAVX2(taps []float32, winR []float32, winI []float32, n int, out *[2]float32)
// Requires: AVX, FMA3
TEXT ·complexFIRDotAVX2(SB), NOSPLIT, $0-88
	MOVQ   taps_base+0(FP), AX
	MOVQ   winR_base+24(FP), CX
	MOVQ   winI_base+48(FP), DX
	MOVQ   n+72(FP), BX
	MOVQ   out+80(FP), SI
	VXORPS Y0, Y0, Y0
	VXORPS Y4, Y4, Y4
	VXORPS Y1, Y1, Y1
	VXORPS Y5, Y5, Y5
	VXORPS Y2, Y2, Y2
	VXORPS Y6, Y6, Y6
	VXORPS Y3, Y3, Y3
	VXORPS Y7, Y7, Y7
	XORQ   DI, DI
	MOVQ   BX, R8
	SUBQ   $0x20, R8

loop32:
	CMPQ        DI, R8
	JG          tail
	VMOVUPS     (AX)(DI*4), Y8
	VMOVUPS     (CX)(DI*4), Y9
	VMOVUPS     (DX)(DI*4), Y10
	VFMADD231PS Y8, Y9, Y0
	VFMADD231PS Y8, Y10, Y4
	VMOVUPS     32(AX)(DI*4), Y8
	VMOVUPS     32(CX)(DI*4), Y9
	VMOVUPS     32(DX)(DI*4), Y10
	VFMADD231PS Y8, Y9, Y1
	VFMADD231PS Y8, Y10, Y5
	VMOVUPS     64(AX)(DI*4), Y8
	VMOVUPS     64(CX)(DI*4), Y9
	VMOVUPS     64(DX)(DI*4), Y10
	VFMADD231PS Y8, Y9, Y2
	VFMADD231PS Y8, Y10, Y6
	VMOVUPS     96(AX)(DI*4), Y8
	VMOVUPS     96(CX)(DI*4), Y9
	VMOVUPS     96(DX)(DI*4), Y10
	VFMADD231PS Y8, Y9, Y3
	VFMADD231PS Y8, Y10, Y7
	ADDQ        $0x20, DI
	JMP         loop32

tail:
	SUBQ $0x08, BX

loop8:
	CMPQ        DI, BX
	JG          reduce
	VMOVUPS     (AX)(DI*4), Y8
	VMOVUPS     (CX)(DI*4), Y9
	VMOVUPS     (DX)(DI*4), Y10
	VFMADD231PS Y8, Y9, Y0
	VFMADD231PS Y8, Y10, Y4
	ADDQ        $0x08, DI
	JMP         loop8

reduce:
	VADDPS       Y1, Y0, Y0
	VADDPS       Y3, Y2, Y2
	VADDPS       Y2, Y0, Y0
	VADDPS       Y5, Y4, Y4
	VADDPS       Y7, Y6, Y6
	VADDPS       Y6, Y4, Y4
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X0, X1, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VEXTRACTF128 $0x00, Y4, X1
	VEXTRACTF128 $0x01, Y4, X2
	VADDPS       X2, X1, X1
	VHADDPS      X1, X1, X1
	VHADDPS      X1, X1, X1
	VMOVSS       X0, (SI)
	VMOVSS       X1, 4(SI)
	VZEROUPPER
	RET
