// Code generated by command: go run main.go -out filter_amd64.s -stubs filter_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

package dsp

// complexFIRDotAVX2 accumulates the multiple-of-eight FIR prefix with AVX2/FMA.
//
//go:noescape
func complexFIRDotAVX2(taps []float32, winR []float32, winI []float32, n int, out *[2]float32)
