// Code generated by command: go run main.go -out foldhop_amd64.s -stubs foldhop_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

package dsp

// foldHopAVX2 is the AVX2 8-bin-block polyphase fold; the Go dispatch handles the scalar tail.
func foldHopAVX2(win []complex64, proto []float32, fold []complex64, kv int, k int, p int)

// foldHop4AVX2 folds four overlapping hop-windows in one proto pass (8-bin blocks); the Go dispatch handles the scalar tail.
func foldHop4AVX2(win []complex64, proto []float32, fold []complex64, kv int, k int, p int, r int)
