// Code generated by command: go run main.go -out foldhop_amd64.s -stubs foldhop_amd64_stub.go -pkg dsp. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

DATA foldhop_idx_lo<>+0(SB)/4, $0x00000000
DATA foldhop_idx_lo<>+4(SB)/4, $0x00000000
DATA foldhop_idx_lo<>+8(SB)/4, $0x00000001
DATA foldhop_idx_lo<>+12(SB)/4, $0x00000001
DATA foldhop_idx_lo<>+16(SB)/4, $0x00000002
DATA foldhop_idx_lo<>+20(SB)/4, $0x00000002
DATA foldhop_idx_lo<>+24(SB)/4, $0x00000003
DATA foldhop_idx_lo<>+28(SB)/4, $0x00000003
GLOBL foldhop_idx_lo<>(SB), RODATA|NOPTR, $32

DATA foldhop_idx_hi<>+0(SB)/4, $0x00000004
DATA foldhop_idx_hi<>+4(SB)/4, $0x00000004
DATA foldhop_idx_hi<>+8(SB)/4, $0x00000005
DATA foldhop_idx_hi<>+12(SB)/4, $0x00000005
DATA foldhop_idx_hi<>+16(SB)/4, $0x00000006
DATA foldhop_idx_hi<>+20(SB)/4, $0x00000006
DATA foldhop_idx_hi<>+24(SB)/4, $0x00000007
DATA foldhop_idx_hi<>+28(SB)/4, $0x00000007
GLOBL foldhop_idx_hi<>(SB), RODATA|NOPTR, $32

// func foldHopAVX2(win []complex64, proto []float32, fold []complex64, kv int, k int, p int)
// Requires: AVX, AVX2, FMA3
TEXT ·foldHopAVX2(SB), NOSPLIT, $0-96
	MOVQ    win_base+0(FP), AX
	MOVQ    proto_base+24(FP), CX
	MOVQ    fold_base+48(FP), DX
	MOVQ    kv+72(FP), BX
	MOVQ    k+80(FP), SI
	MOVQ    p+88(FP), DI
	MOVQ    SI, R8
	SHLQ    $0x03, R8
	SHLQ    $0x02, SI
	VMOVUPS foldhop_idx_lo<>+0(SB), Y0
	VMOVUPS foldhop_idx_hi<>+0(SB), Y1
	XORQ    R9, R9

binloop:
	CMPQ   R9, BX
	JGE    done
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3
	MOVQ   R9, R10
	SHLQ   $0x03, R10
	ADDQ   AX, R10
	MOVQ   R9, R11
	SHLQ   $0x02, R11
	ADDQ   CX, R11
	XORQ   R12, R12

taploop:
	CMPQ        R12, DI
	JGE         tapdone
	VMOVUPS     (R10), Y4
	VMOVUPS     32(R10), Y5
	VMOVUPS     (R11), Y6
	VPERMPS     Y6, Y0, Y7
	VPERMPS     Y6, Y1, Y6
	VFMADD231PS Y4, Y7, Y2
	VFMADD231PS Y5, Y6, Y3
	ADDQ        R8, R10
	ADDQ        SI, R11
	INCQ        R12
	JMP         taploop

tapdone:
	MOVQ    R9, R10
	SHLQ    $0x03, R10
	ADDQ    DX, R10
	VMOVUPS Y2, (R10)
	VMOVUPS Y3, 32(R10)
	ADDQ    $0x08, R9
	JMP     binloop

done:
	VZEROUPPER
	RET

// func foldHop4AVX2(win []complex64, proto []float32, fold []complex64, kv int, k int, p int, r int)
// Requires: AVX, AVX2, FMA3
TEXT ·foldHop4AVX2(SB), NOSPLIT, $8-104
	MOVQ    win_base+0(FP), AX
	MOVQ    proto_base+24(FP), CX
	MOVQ    fold_base+48(FP), DX
	MOVQ    kv+72(FP), BX
	MOVQ    k+80(FP), SI
	MOVQ    p+88(FP), DI
	MOVQ    r+96(FP), R8
	MOVQ    SI, R9
	SHLQ    $0x03, R9
	SHLQ    $0x02, SI
	SHLQ    $0x03, R8
	VMOVUPS foldhop_idx_lo<>+0(SB), Y0
	VMOVUPS foldhop_idx_hi<>+0(SB), Y1
	XORQ    R10, R10

binloop4:
	CMPQ   R10, BX
	JGE    done4
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3
	VXORPS Y4, Y4, Y4
	VXORPS Y5, Y5, Y5
	VXORPS Y6, Y6, Y6
	VXORPS Y7, Y7, Y7
	VXORPS Y8, Y8, Y8
	VXORPS Y9, Y9, Y9
	MOVQ   R10, R11
	SHLQ   $0x03, R11
	ADDQ   AX, R11
	LEAQ   (R11)(R8*1), R12
	LEAQ   (R12)(R8*1), R13
	LEAQ   (R13)(R8*1), R14
	MOVQ   R10, R15
	SHLQ   $0x02, R15
	ADDQ   CX, R15
	XORQ   BP, BP

taploop4:
	CMPQ        BP, DI
	JGE         tapdone4
	VMOVUPS     (R15), Y10
	VPERMPS     Y10, Y0, Y12
	VPERMPS     Y10, Y1, Y13
	VMOVUPS     (R11), Y10
	VMOVUPS     32(R11), Y11
	VFMADD231PS Y10, Y12, Y2
	VFMADD231PS Y11, Y13, Y3
	VMOVUPS     (R12), Y10
	VMOVUPS     32(R12), Y11
	VFMADD231PS Y10, Y12, Y4
	VFMADD231PS Y11, Y13, Y5
	VMOVUPS     (R13), Y10
	VMOVUPS     32(R13), Y11
	VFMADD231PS Y10, Y12, Y6
	VFMADD231PS Y11, Y13, Y7
	VMOVUPS     (R14), Y10
	VMOVUPS     32(R14), Y11
	VFMADD231PS Y10, Y12, Y8
	VFMADD231PS Y11, Y13, Y9
	ADDQ        R9, R11
	ADDQ        R9, R12
	ADDQ        R9, R13
	ADDQ        R9, R14
	ADDQ        SI, R15
	INCQ        BP
	JMP         taploop4

tapdone4:
	MOVQ    R10, R11
	SHLQ    $0x03, R11
	ADDQ    DX, R11
	VMOVUPS Y2, (R11)
	VMOVUPS Y3, 32(R11)
	LEAQ    (R11)(R9*1), R11
	VMOVUPS Y4, (R11)
	VMOVUPS Y5, 32(R11)
	LEAQ    (R11)(R9*1), R11
	VMOVUPS Y6, (R11)
	VMOVUPS Y7, 32(R11)
	LEAQ    (R11)(R9*1), R11
	VMOVUPS Y8, (R11)
	VMOVUPS Y9, 32(R11)
	ADDQ    $0x08, R10
	JMP     binloop4

done4:
	VZEROUPPER
	RET
